version: '3.8'

services:
  app:
    image: openjdk:21-jdk-slim
    container_name: AP-5
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ./gradlew bootRun