version: '3.8'

services:
  app:
    image: public.ecr.aws/d3d9m8w4/ap-5:latest  # Używa najnowszego obrazu z publicznego ECR
    container_name: AP-5
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
    restart: always