# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/libs/

  test:
    runs-on: self-hosted
    needs: build 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV
  #    - name: Run tests
  #      run: ./gradlew test

  docker-build:
    needs: test
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

##TODO wrzucić variable ap-5 jako zmienna środowiskowa
      - name: URL Identify Docker image
        run: |
          IMAGE_URI=public.ecr.aws/d3d9m8w4/${{ vars.REPOSITORY_NAME }}:latest
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          
          # Budowanie obrazu Docker z wykorzystaniem Dockerfile
          docker build -t $IMAGE_URI -f Dockerfile .
# Was tagged ? 
      - name: Tag Docker image
        run: |
          # Tagowanie obrazu dla publicznego rejestru ECR
          docker tag $IMAGE_URI public.ecr.aws/d3d9m8w4/${{ vars.REPOSITORY_NAME }}:latest

      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: .

      
  
  docker-test:
      needs: docker-build
      runs-on: self-hosted

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Download Docker image artifact
          uses: actions/download-artifact@v4
          with:
            name: docker-image
        #Todo zaplanować testy

  docker-push:
    needs: docker-test
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Add AWS CLI to PATH
        run: echo "/usr/local/bin" >> $GITHUB_PATH 

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Run AWS CLI version
        run: aws --version

      - name: Run which AWS CLI
        run: which aws

      - name: Show ECR repositories
        run: |
          aws ecr-public describe-repositories --region us-east-1 --output table

      - name: Check ECR password image to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1

      - name: Debug AWS Credentials
        run: |
          echo "AWS Region: ${{ secrets.AWS_REGION }}"
          aws sts get-caller-identity
          aws ecr-public describe-repositories --region us-east-1

      - name: AWS ECR auth image to Amazon ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/d3d9m8w4
        
      - name: Docker list images
        run: |
          docker image ls
      
      - name: Set IMAGE_URI
        run: echo "IMAGE_URI=public.ecr.aws/d3d9m8w4/${{ vars.REPOSITORY_NAME }}:latest" >> $GITHUB_ENV

      - name: Display IMAGE_URI
        run: echo "$IMAGE_URI"
  
      - name: Push Docker image to Amazon ECR
        run: |
            run: |
              IMAGE_URI="public.ecr.aws/d3d9m8w4/${{ vars.REPOSITORY_NAME }}:latest"
              docker push $IMAGE_URI